### ISSUE TITLE
Excel utilizado en plugin

### ISSUE THREAD

**Issue by fraagucan2** [laramorilla/project-program#12]
Buenas, soy del grupo de Gestión de programa del grupo 1 de la asignatura. Me gustaría saber que excel estais utilizando para hacer vuestro plugin, porque los unicos excels que tenemos son los que estan en la versión antigua del plugin que viene instalado en el wordpress: "programme-pre-v8.xlsx" y "programme-main-v9.xlsx". Pero ese plugin esta anticuado, la ultima versión del plugin es la que estaba en GitHub. ¿Existen excels más actuales o también estais utilizando esos dos excels?

Un saludo

**Comment by samusfc** [comment]
Buenas, nuestro grupo está usando la versión antigua del plugin con esos excels. No sabemos si hay unos excels más actualizados.

Un saludo.
