### ISSUE TITLE
Creación de nuevo botón para prueba

### ISSUE THREAD

**Issue by laramorilla** [laramorilla/project-program#27]
Prioridad: media
Estado: pendiente
Descripción: Se ha de crear un nuevo botón para el sistema, este botón es un botón simple para que se muestre el proceso de gestión de código

**Comment by Felix866** [comment]
Descripción: Se ha relizado un botón para la funcionalidad 5, todo funciona correctamente.
close: Creación de nuevo botón para prueba #27
