### ISSUE TITLE
Funcionamiento erroneo de plugin

### ISSUE THREAD

**Issue by laramorilla** [laramorilla/project-program#4]
Título: Funcionamiento erroneo de plugin
Prioridad: alto
Estado: pendiente
Descripción: cuando se lleva a cabo la activación del plugin de programa, hay que crear una nueva pagina para tras activar este plugin mostrar su funcionamiento. En esta página nueva que hemos creado tenemos que poner la siguiente linea de código:
[write_long_program] esta linea de código debe impirmir por pantalla cuando se selecciona la pagina del plugin, este mismo funcionando. Tras intentar hacer que se muestre nos aparece el siguiente error:

![whatsapp image 2017-12-02 at 14 36 03](https://user-images.githubusercontent.com/32852642/33518574-3ca3232c-d797-11e7-88a2-7f23ccfcc5e1.jpeg)

Queda pendiente encontrar la solución y el porque de este suceso.

Etiquetas: good firt issue

**Comment by Felix866** [comment]
El problema está en que al querer cargar el archivo xlsx, no encuentra este en la ruta. Se soluciona cambiando en el archivo program-manager.php la ruta donde se encuentra el xlsx.

function write_program(){
	date_default_timezone_set('UTC');
	wp_enqueue_style( 'my-style' );
	wp_enqueue_script( 'my-script' );

	**$xlsx = new XLSXReader('./wp-content/plugins/program-manager/programme-main-v9.xlsx');
  $xlsxPRE = new XLSXReader('./wp-content/plugins/program-manager/programme-pre-v8.xlsx');**
