### ISSUE TITLE
Api programa

### ISSUE THREAD

**Issue by alexgs922** [laramorilla/project-program#5]
Titulo: Api de programa.
Prioridad: alto.
Estado: pendiente.
Descripción: Solicito la api del programa para poder consumirla y desarrollar a partir de los datos proporcionados en dicha api.

**Comment by fblanco89** [comment]
Debido a las dificultades de la realización de esta API, hemos proporcionado a este equipo a través de la wiki de EGC información con la que puede obtener datos básicos a través de la API de wordpress: https://1984.lsi.us.es/wiki-egc/index.php/Gesti%C3%B3n_del_programa_-_17_18_-_G2

**Comment by alexgs922** [comment]
Intentaremos desarrollar en base a lo que nos habéis aportado a estas alturas sin llegar a asegurar un desarrollo completo ya y funcional 100% puesto que no era la API que se solicitó.

No obstante,si no se llega al objetivo no supondrá cuello de botella porque se cuenta con una bd del archivo excel.
